### PR TITLE
Add pyx file to pypi

### PR DESCRIPTION
**Pull request by davidbrochart**

### CODE REVIEW

**Comment by kylebarron** [comment]
Sorry I'm not used to Cython packaging. This is needed for source builds?

**Comment by davidbrochart** [comment]
Yes, I'm trying to package pymartini for conda: https://github.com/conda-forge/staged-recipes/pull/12728
It works now because I get the tarball from GitHub, but the recommended way is to get it from PyPI, and it just misses this file to build the extension.

**Comment by kylebarron** [comment]
Wow thanks! I've struggled with Conda before for _pure-Python_ packages, so I decided I didn't want to even try for a Cython package.

I pushed 0.3.2 to PyPI: https://pypi.org/project/pymartini/0.3.2/

**Comment by davidbrochart** [comment]
Awesome, thanks a lot! I will update the recipe.

**Comment by davidbrochart** [comment]
Do you want me to add you as a maintainer of the feedstock?

**Comment by kylebarron** [comment]
That's fine. Hopefully future updates are auto-mergeable 😅

**Comment by davidbrochart** [comment]
Yes, it's usually the case. You will need to confirm that you agree to be a maintainer.

**Pull request merged**
